kind: Secret
apiVersion: v1
metadata:
  name: fake-secret
  namespace: fybrik-airbyte-sample
stringData:
  access_key_id: "cae190fe77674a6a9fa92863d6d4e814"
  secret_access_key: "88e2f522b47c4224859a21fc5595dacdcf0629b7bebbf0d9"
type: Opaque
