# Deploys a new Namespace for the MinIO Pod
apiVersion: v1
kind: Namespace
metadata:
  name: minio # Change this value if you want a different namespace name
  labels:
    name: minio # Change this value to match metadata.name
---
# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].m>
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a >
#
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio # Change this value to match the namespace metadata.name
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
      - /bin/bash
      - -c
    envs:
    - name: MINIO_ROOT_USER
      value: "minioadmin"
    - name: MINIO_ROOT_PASSWORD
      value: "minioadmin"
      args:
        - minio server /data --console-address :9090
      volumeMounts:
      - mountPath: /data
        name: localvolume # Corresponds to the `spec.volumes` Persistent Volume
        volumes:
          - name: localvolume
            hostPath: # MinIO generally recommends using locally-attached volumes
              path: /tmp/minio/data # Specify a path to a local drive or volume on the K>
              type: DirectoryOrCreate # The path to the last directory must exist