apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: sm-s3-data
  namespace: kafka-s3
spec:
  details:
    dataFormat: json
    connection:
      name: s3
      s3:
        endpoint: "http://s3.eu.cloud-object-storage.appdomain.cloud"
        safeBucket: "smartmanufacturing-safe-bucket"
        unsafeBucket: "smartmanufacturing-unsafe-bucket"
        namespace: fybrik-system
        credentialsFile: credentials
  secretRef:
    name: credentials
    namespace: fybrik-system
  metadata:
    name:  s3-store
    geography: UK
    tags:
      sm: true
    columns:
      - name: id
        tags:
          PII: true
          blocked: true
