# ClusterRole katalog-viewer allows viewing assets.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-viewer
rules:
- apiGroups: ["status.fybrik.io"]
  resources: ["situations"]
  verbs: ["get", "list", "watch"]
---
# Grant katalog-system services the katalog-viewer ClusterRole.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-viewer
roleRef:
  kind: ClusterRole
  name: katalog-viewer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:unauthenticated
  apiGroup: rbac.authorization.k8s.io