apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: s3-userdata
  namespace: fybrik-airbyte-sample
spec:
  secretRef: 
    name: s3-credentials
  details:
    dataFormat: json
    connection:
      name: s3
      s3:
        connector: "airbyte/destination-s3"
        s3_path_format: ${NAMESPACE}/${YEAR}_${MONTH}_${DAY}_${EPOCH}_
        s3_endpoint: "http://s3.eu.cloud-object-storage.appdomain.cloud"
        s3_bucket_name: "heir-test1"
        s3_bucket_path: "from-connector_new"
        s3_bucket_region: ""
        format:
           format_type: CSV
           flattening: No flattening
  metadata:
    name: test data
    geography: theshire 
    tags:
      finance: true
    columns:
      - name: first_name
        tags:
          PII: true
      - name: last_name
        tags:
          PII: true
      - name: email
        tags:
          PII: true
      - name: birthdate
        tags:
          PII: true
