# Try it with `helm install --generate-name --dry-run -f helm/abm/values.sample.yaml helm/abm`
labels:
  name: 012d42539692bba841a7
  namespace: default
uuid: "12345678"
assets:
- args:
  - connection:
      name: file
      file:
        connector: "airbyte/source-file"
        dataset_name: userdata
        format: parquet
        url: "https://github.com/Teradata/kylo/raw/master/samples/sample-data/parquet/userdata2.parquet"
        provider:
          storage: HTTPS
  assetID: "userdata"
