apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-to-s3.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-to-s3.name" . }}
    helm.sh/chart: {{ include "kafka-to-s3.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-to-s3.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kafka-to-s3.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}    
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: {{ include "kafka-to-s3.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            # Define the environment variable to set the situational status
          volumeMounts:
            - readOnly: true
              mountPath: /etc/conf
              name: config
            - readOnly: true
              mountPath: /etc/confmap
              name: situationstatus
      volumes:
        - name: config
          configMap:
            name: {{ include "kafka-to-s3.fullname" . }}
        - name: situationstatus
          configMap:
            name: situationstatus
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
